name: End-to-End Tests

on:
  pull_request:
    paths: ['src/**', 'action.yml', 'examples/**']
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build action
        run: npm run build

      - name: Debug - Check built files
        run: |
          echo "=== CHECKING BUILT FILES ==="
          ls -la dist/
          echo "---"
          echo "Checking main entry point:"
          head -20 dist/index.js
          echo "---"
          echo "Checking if action.yml points to correct file:"
          grep -A 5 "runs:" action.yml

      - name: Debug - Check files
        run: |
          echo "Checking example files..."
          ls -la examples/app/
          ls -la examples/infra/
          cat examples/app/requirements.txt
          echo "---"
          head -10 examples/infra/main.tf

      - name: Debug - Test scanners manually
        run: |
          echo "Testing Trivy installation..."
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.48.0
          trivy --version
          
          echo "Testing Trivy scan..."
          trivy fs --format json examples/app/ || echo "Trivy scan failed"
          
          echo "Testing Checkov installation..."
          # Use pip installation with 3.1.0 (which works)
          echo "Installing Checkov via pip..."
          pip install checkov==3.1.0
          checkov --version || echo "Checkov installation failed"
          
          echo "Testing Checkov scan..."
          checkov -d examples/infra/ --output json --output-file-path checkov-debug || echo "Checkov scan failed"
          
          echo "Testing Conftest installation..."
          # Use a version that definitely exists
          wget -O conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v0.55.0/conftest_0.55.0_Linux_x86_64.tar.gz
          tar -xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin/
          chmod +x /usr/local/bin/conftest
          conftest --version
          
          echo "Testing Conftest scan..."
          conftest test examples/infra/ --policy policies/conftest/ --parser hcl2 --output json || echo "Conftest scan failed"

      - name: Test DevSecOps PR Gate
        id: devsecops-pr-gate
        uses: ./
        with:
          paths-app: examples/app/
          paths-iac: examples/infra/
          fail-on: high
          opa-policy-path: policies/conftest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Test with minimal inputs
        id: test-minimal
        uses: ./
        with:
          paths-app: examples/app/
          paths-iac: examples/infra/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Debug - Check minimal test outputs
        if: always()
        run: |
          echo "=== MINIMAL TEST OUTPUTS ==="
          echo "Minimal test outcome: ${{ steps.test-minimal.outcome }}"
          echo "Minimal test conclusion: ${{ steps.test-minimal.conclusion }}"
          echo "Minimal test outputs:"
          echo "  has-blockers: '${{ steps.test-minimal.outputs.has-blockers }}'"
          echo "  trivy-high: '${{ steps.test-minimal.outputs.trivy-high }}'"

      - name: Debug - Check action logs
        if: always()
        run: |
          echo "=== ACTION DEBUG INFO ==="
          echo "Action step exit code: ${{ steps.devsecops-pr-gate.outcome }}"
          echo "Action step conclusion: ${{ steps.devsecops-pr-gate.conclusion }}"
          echo "All outputs:"
          echo "  comment-url: '${{ steps.devsecops-pr-gate.outputs.comment-url }}'"
          echo "  trivy-high: '${{ steps.devsecops-pr-gate.outputs.trivy-high }}'"
          echo "  trivy-critical: '${{ steps.devsecops-pr-gate.outputs.trivy-critical }}'"
          echo "  checkov-high: '${{ steps.devsecops-pr-gate.outputs.checkov-high }}'"
          echo "  checkov-critical: '${{ steps.devsecops-pr-gate.outputs.checkov-critical }}'"
          echo "  opa-deny-count: '${{ steps.devsecops-pr-gate.outputs.opa-deny-count }}'"
          echo "  has-blockers: '${{ steps.devsecops-pr-gate.outputs.has-blockers }}'"

      - name: Debug - Check outputs
        run: |
          echo "Comment URL: ${{ steps.devsecops-pr-gate.outputs.comment-url }}"
          echo "Trivy High: ${{ steps.devsecops-pr-gate.outputs.trivy-high }}"
          echo "Trivy Critical: ${{ steps.devsecops-pr-gate.outputs.trivy-critical }}"
          echo "Checkov High: ${{ steps.devsecops-pr-gate.outputs.checkov-high }}"
          echo "Checkov Critical: ${{ steps.devsecops-pr-gate.outputs.checkov-critical }}"
          echo "OPA Deny Count: ${{ steps.devsecops-pr-gate.outputs.opa-deny-count }}"
          echo "Has Blockers: ${{ steps.devsecops-pr-gate.outputs.has-blockers }}"

      - name: Verify outputs
        run: |
          echo "=== DEBUGGING OUTPUT ==="
          echo "Expected: has-blockers should be 'true'"
          echo "Actual: has-blockers = '${{ steps.devsecops-pr-gate.outputs.has-blockers }}'"
          echo "Trivy High: '${{ steps.devsecops-pr-gate.outputs.trivy-high }}'"
          echo "Trivy Critical: '${{ steps.devsecops-pr-gate.outputs.trivy-critical }}'"
          echo "Checkov High: '${{ steps.devsecops-pr-gate.outputs.checkov-high }}'"
          echo "Checkov Critical: '${{ steps.devsecops-pr-gate.outputs.checkov-critical }}'"
          echo "OPA Deny Count: '${{ steps.devsecops-pr-gate.outputs.opa-deny-count }}'"
          
          if [ "${{ steps.devsecops-pr-gate.outputs.has-blockers }}" != "true" ]; then
            echo "FAIL: Expected to find blockers in examples"
            echo "This might be due to scanner installation issues in the GitHub Actions environment"
            echo "The action should find:"
            echo "- Trivy: vulnerable requests package (2.19.1)"
            echo "- Checkov: SSH open to world (0.0.0.0/0)"
            echo "- OPA: SSH policy violation"
            exit 1
          fi
          
          echo "PASS: Test passed - found expected security issues" 