name: Test DevSecOps PR Gate Action

on:
  pull_request:
    paths: ['src/**', 'action.yml', 'examples/**']
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build action
        run: npm run build



      - name: Test Action with Security Issues (Should Fail)
        id: test-with-issues
        uses: ./
        continue-on-error: true
        with:
          paths-app: examples/app/
          paths-iac: examples/infra/
          fail-on: high
          opa-policy-path: policies/conftest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Action with Minimal Inputs
        id: test-minimal
        uses: ./
        continue-on-error: true
        with:
          paths-app: examples/app/
          paths-iac: examples/infra/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Tests
        if: always()
        run: |
          # Check main test
          if [ "${{ steps.test-with-issues.outputs.has-blockers }}" != "true" ]; then
            echo "FAIL: Main test should detect security issues"
            exit 1
          fi
          
          if [ "${{ steps.test-with-issues.outcome }}" != "failure" ]; then
            echo "FAIL: Main test should fail when security issues found"
            exit 1
          fi
          
          # Check minimal test
          if [ "${{ steps.test-minimal.outputs.has-blockers }}" != "true" ]; then
            echo "FAIL: Minimal test should detect security issues"
            exit 1
          fi
          
          echo "PASS: All tests completed successfully" 